;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Oct 17 2022
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

paul john

DATA SEGMENT
   PORTA EQU 0F0H;
   PORTB EQU 0F2H;
   PORTC EQU 0F4H;
DATA ENDS


CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE
	MOV AX, DATA
	MOV DS, AX
	
	ORG 0000H

START:


INPUT_C:
      MOV DX, PORTC
      IN AL, DX
      CMP AL, 01H
      JE LED_PATTERN
      CMP AL, 02H
      JE SEG_COUNT
      JMP INPUT_C

LED_PATTERN:

  MOV DX, PORTA
  MOV AL, 01H
  OUT DX,AL
  CALL DELAY_1MS   
  SHIFT_LEFT:
	SHL AL, 01H
	OUT DX,AL
	CALL DELAY_1MS   
	CMP AL, 10000000B
	JE START
	JMP SHIFT_LEFT
 

SEG_COUNT:
	
  MOV DX, PORTB
  
  MOV AL, 00111111B    ;display 0
  OUT DX, AL
  CALL DELAY_1MS    
  
  MOV AL, 00000110B    ;display 1
  OUT DX, AL
  CALL DELAY_1MS    
  MOV AL, 01011011B    ;display 2
  OUT DX, AL
  CALL DELAY_1MS    
  
   MOV AL, 01001111B    ;display 3
  OUT DX, AL
  CALL DELAY_1MS    
   MOV AL, 01100110B    ;display 4
  OUT DX, AL
  CALL DELAY_1MS    
  
   MOV AL, 01101101B    ;display 5
  OUT DX, AL
  CALL DELAY_1MS    
  
   MOV AL, 01111101B    ;display 6
  OUT DX, AL
  CALL DELAY_1MS    
  
   MOV AL, 00000111B    ;display 7
  OUT DX, AL
  CALL DELAY_1MS    
  
   MOV AL, 01111111B    ;display 8
  OUT DX, AL
  CALL DELAY_1MS    
                  
               
  MOV AL, 01101111B    ;display 9
  OUT DX, AL
  CALL DELAY_1MS    
  
  MOV AL, 00111111B    ;display 0
  OUT DX, AL
  CALL DELAY_1MS    
  JMP START

	

DELAY_1MS:
   MOV BX, 03FCAH
L1:
   DEC BX
   NOP
   JNZ L1
   RET
RET


EXIT: 

CODE    ENDS


END 